spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: journal_db_test
      auto-index-creation: true
  redis:
    host: localhost
    port: 6379
  application:
    name: JOURNAL-SERVICE
server:
  port: 8088
stock:
  apiKey: 66c03b19d9a207.01769437
weather:
  apiKey: 484eb5b0ff73762ee1ab84862b62f3fd
eleven:
  apiKey: sk_6555b4a11527cab2693fcdf8719cc842b584a86ad0bcbe13








